<?php

namespace AppBundle\Repository;

/**
 * ArticleCRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleCRRepository extends \Doctrine\ORM\EntityRepository
{
}
