<?php

namespace AppBundle\Repository;

/**
 * ArticleLRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleLRepository extends \Doctrine\ORM\EntityRepository
{

	public function countLikes($post)
    {
        return $this->createQueryBuilder('l')
		    ->select('count(l.id)')
		    ->where('l.post = :post')
		    ->setParameter('post', $post)
		    ->getQuery()
		    ->getSingleScalarResult();
    }
}
