<?php

namespace AppBundle\Repository;

/**
 * ArticleMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleMRepository extends \Doctrine\ORM\EntityRepository
{
}
