<?php

namespace AppBundle\Repository;

/**
 * ArticleMCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleMCRepository extends \Doctrine\ORM\EntityRepository
{
}
