<?php

namespace AppBundle\Repository;

/**
 * ArticleCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleCRepository extends \Doctrine\ORM\EntityRepository
{
}
