<?php

namespace AppBundle\Repository;

/**
 * CommentRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRRepository extends \Doctrine\ORM\EntityRepository
{
}
