<?php

namespace AppBundle\Repository;

/**
 * ConversationRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRRepository extends \Doctrine\ORM\EntityRepository
{
}
