<?php

namespace AppBundle\Repository;

/**
 * DiscussionCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscussionCRepository extends \Doctrine\ORM\EntityRepository
{
}
