<?php

namespace AppBundle\Repository;

/**
 * NotifierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotifierRepository extends \Doctrine\ORM\EntityRepository
{
}
