<?php

namespace AppBundle\Repository;

/**
 * PhotoCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoCRepository extends \Doctrine\ORM\EntityRepository
{
}
