<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchMatchingPosts($searchText)
    {
    	return $this->createQueryBuilder('p')
               ->where('p.title LIKE :input OR p.body LIKE :input')
               ->setParameter('input', '%' .$searchText.'%')
               ->setMaxResults(10)
               ->getQuery()
               ->getResult();
    }

}
